apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportboxadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reportboxadmin
  template:
    metadata:
      labels:
        name: reportboxadmin
    spec:
      containers:
        - name: application
          image: mramperage/reportboxadmin:development
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7614
