kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
  - name: ssh and deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.40.203
      username:
        from_secret: ssh_login
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 10m
      script:
        - echo =========Delete========
        - cd /opt/Projects
        - rm -r ReportBoxAdministartionService
        - echo =========Clone=======
        - git clone http://192.168.7.70:31644/okugario/ReportBoxAdministartionService.git
        - echo =========Build=========
        - cd /opt/Projects/ReportBoxAdministartionService
        - docker build -t okugario/reportboxadmin:dev1 .
        - echo =========Run==========
        - docker login
        - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
        - docker push okugario/reportboxadmin:dev1
        - echo ========DeleteKube====
        - kubectl delete deployment administartionservice
        - echo =========Done=========
        - cd /opt/Projects/ReportBoxAdministartionService
        - kubectl apply -f service.yaml
        - kubectl apply -f deployment.yaml

trigger:
  branch:
    - main
  event:
    - push
