apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: report-test
  template:
    metadata:
      labels:
        name: report-test
    spec:
      containers:
        - name: application
          image: okugario/report-test:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7613
